CREATE TABLE IF NOT EXISTS b_otus_company_visits (
    ID INT NOT NULL AUTO_INCREMENT,
    COMPANY_ID INT NOT NULL,
    VISIT_DATE DATE NOT NULL,
    MANAGER VARCHAR(255),
    COMMENTS TEXT,
    PRIMARY KEY (ID)
);